version: "3"

services:
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_PASSWORD: adverity
      POSTGRES_USER: adverity
      POSTGRES_DB: adverity
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: on-failure

  adverity:
    build: .
    environment:
      DJANGO_SETTINGS_MODULE: adverity.settings_docker
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: on-failure